source "https://rubygems.org"

gem "pry"
gem "rake"
gem "rerun"
gem "faker"
gem "webrick"
gem "sinatra"
gem "sqlite3"
gem "rack-cors"
gem "require_all"
gem "rack-contrib"
gem "activerecord"
gem "sinatra-flash"
gem "sinatra-activerecord"