development:
  adapter: sqlite3
  database: db/development.sqlite3

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3

production:
  adapter: postgresql
  database: production_database_name
  host: production_database_host
  port: production_database_port
  username: production_database_username
  password: production_database_password
